trigger:

  branches:
    exclude:
      - readme*
      - temp-*
      - exp-*

  paths:
    exclude:
      - README.md
      - docs/**
      - scripts/configurator/**

jobs:
  - job: interactive_gcc84
    container: 'vvaltchev/tilck-ci-build:v5'
    pool:
      vmImage: 'ubuntu-20.04'
    variables:
      CI: 1
      TCROOT: /tc/toolchain2-gcc84
      GTEST_SHUFFLE: 0
      TILCK_NO_LOGO: 1
      GCC_TC_VER: 8.4.0
      CMAKE_ARGS: >
        -DEXTRA_TCC=1
        -DEXTRA_VIM=1
        -DFB_CONSOLE_BANNER=0
        -DFB_CONSOLE_CURSOR_BLINK=0
        -DBOOT_INTERACTIVE=0
        -DPREFERRED_GFX_MODE_W=640
        -DPREFERRED_GFX_MODE_H=480
        -DKMALLOC_FREE_MEM_POISONING=1
    steps:
      - script: printenv
        displayName: Dump env
      - script: ./scripts/build_generators/gcc_gcov
        displayName: Run CMake
      - script: make -j
        displayName: Build the kernel
      - script: make -j gtests
        displayName: Build the unit tests
      - script: ./build/gtests
        displayName: Run the unit tests
      - script: ./build/st/run_all_tests -c
        displayName: Run the system tests
      - script: ./build/st/run_interactive_test -a
        displayName: Run the interactive tests

  - job: gcc_8_4
    container: 'vvaltchev/tilck-ci-build:v5'
    pool:
      vmImage: 'ubuntu-20.04'
    variables:
      CI: 1
      TCROOT: /tc/toolchain2-gcc84
      GTEST_SHUFFLE: 0
      TILCK_NO_LOGO: 1
      GCC_TC_VER: 8.4.0
      CMAKE_ARGS: >
        -DKERNEL_UBSAN=1
        -DKMALLOC_FREE_MEM_POISONING=1
    strategy:
      matrix:
        debug:
          GEN: 'gcc'
        release:
          GEN: 'gcc_rel'
        fast_release:
          GEN: 'gcc_fast_rel'
        arch_gtests:
          GEN: 'gcc_arch_gtests'
        nocow:
          GEN: 'gcc_nocow'
        no_nested_irq_tracking:
          GEN: 'gcc_no_nested_irq_tracking'
        minimal:
          GEN: 'minimal'
        small-offt:
          GEN: 'gcc_small_offt'
    steps:
      - script: printenv
        displayName: Dump env
      - script: ./scripts/build_generators/$(GEN)
        displayName: Run CMake
      - script: make -j
        displayName: Build the kernel
      - script: make -j gtests
        displayName: Build the unit tests
      - script: ./build/gtests
        displayName: Run the unit tests
      - script: ./build/st/run_all_tests -c
        displayName: Run the system tests

  - job: gcc_9_3
    container: 'vvaltchev/tilck-ci-build:v5'
    pool:
      vmImage: 'ubuntu-20.04'
    variables:
      CI: 1
      TCROOT: /tc/toolchain2-gcc93
      GTEST_SHUFFLE: 0
      TILCK_NO_LOGO: 1
      GCC_TC_VER: 9.3.0
      CMAKE_ARGS: >
        -DKERNEL_UBSAN=1
        -DKMALLOC_FREE_MEM_POISONING=1
    strategy:
      matrix:
        debug:
          GEN: 'gcc'
        release:
          GEN: 'gcc_rel'
        fast_release:
          GEN: 'gcc_fast_rel'
        arch_gtests:
          GEN: 'gcc_arch_gtests'
        nocow:
          GEN: 'gcc_nocow'
        no_nested_irq_tracking:
          GEN: 'gcc_no_nested_irq_tracking'
        minimal:
          GEN: 'minimal'
        small-offt:
          GEN: 'gcc_small_offt'
    steps:
      - script: printenv
        displayName: Dump env
      - script: ./scripts/build_generators/$(GEN)
        displayName: Run CMake
      - script: make -j
        displayName: Build the kernel
      - script: make -j gtests
        displayName: Build the unit tests
      - script: ./build/gtests
        displayName: Run the unit tests
      - script: ./build/st/run_all_tests -c
        displayName: Run the system tests

  - job: gcc_10_3
    container: 'vvaltchev/tilck-ci-build:v5'
    pool:
      vmImage: 'ubuntu-20.04'
    variables:
      CI: 1
      TCROOT: /tc/toolchain2-gcc103
      GTEST_SHUFFLE: 0
      TILCK_NO_LOGO: 1
      GCC_TC_VER: 10.3.0
      CMAKE_ARGS: >
        -DKERNEL_UBSAN=1
        -DKMALLOC_FREE_MEM_POISONING=1
    strategy:
      matrix:
        debug:
          GEN: 'gcc'
        release:
          GEN: 'gcc_rel'
        fast_release:
          GEN: 'gcc_fast_rel'
        arch_gtests:
          GEN: 'gcc_arch_gtests'
        nocow:
          GEN: 'gcc_nocow'
        no_nested_irq_tracking:
          GEN: 'gcc_no_nested_irq_tracking'
        minimal:
          GEN: 'minimal'
        small-offt:
          GEN: 'gcc_small_offt'
    steps:
      - script: printenv
        displayName: Dump env
      - script: ./scripts/build_generators/$(GEN)
        displayName: Run CMake
      - script: make -j
        displayName: Build the kernel
      - script: make -j gtests
        displayName: Build the unit tests
      - script: ./build/gtests
        displayName: Run the unit tests
      - script: ./build/st/run_all_tests -c
        displayName: Run the system tests

  - job: gcc_11_3
    container: 'vvaltchev/tilck-ci-build:v5'
    pool:
      vmImage: 'ubuntu-20.04'
    variables:
      CI: 1
      TCROOT: /tc/toolchain2-gcc113
      GTEST_SHUFFLE: 0
      TILCK_NO_LOGO: 1
      GCC_TC_VER: 11.3.0
      CMAKE_ARGS: >
        -DKERNEL_UBSAN=1
        -DKMALLOC_FREE_MEM_POISONING=1
    strategy:
      matrix:
        debug:
          GEN: 'gcc'
        release:
          GEN: 'gcc_rel'
        fast_release:
          GEN: 'gcc_fast_rel'
        arch_gtests:
          GEN: 'gcc_arch_gtests'
        nocow:
          GEN: 'gcc_nocow'
        no_nested_irq_tracking:
          GEN: 'gcc_no_nested_irq_tracking'
        minimal:
          GEN: 'minimal'
        small-offt:
          GEN: 'gcc_small_offt'
    steps:
      - script: printenv
        displayName: Dump env
      - script: ./scripts/build_generators/$(GEN)
        displayName: Run CMake
      - script: make -j
        displayName: Build the kernel
      - script: make -j gtests
        displayName: Build the unit tests
      - script: ./build/gtests
        displayName: Run the unit tests
      - script: ./build/st/run_all_tests -c
        displayName: Run the system tests

  - job: syscc
    container: 'vvaltchev/tilck-ci-build:v5'
    pool:
      vmImage: 'ubuntu-20.04'
    variables:
      CI: 1
      TCROOT: /tc/toolchain2-gcc84
      GTEST_SHUFFLE: 0
      TILCK_NO_LOGO: 1
      GCC_TC_VER: 8.4.0
      CMAKE_ARGS: >
        -DKMALLOC_FREE_MEM_POISONING=1
    strategy:
      matrix:
        gcc:
          GEN: 'gcc_syscc'
        clang:
          GEN: 'clang_wconv'
        clang_tc_isystem:
          GEN: 'clang_tc_isystem'
        clang_small_offt:
          GEN: 'clang_small_offt'
    steps:
      - script: printenv
        displayName: Dump env
      - script: ./scripts/build_generators/$(GEN)
        displayName: Run CMake
      - script: make -j
        displayName: Build the kernel
      - script: make -j gtests
        displayName: Build the unit tests
      - script: ./build/gtests
        displayName: Run the unit tests
      - script: ./build/st/run_all_tests -c
        displayName: Run the system tests

  - job: gcc_8_4_x86_64
    container: 'vvaltchev/tilck-ci-build:v5'
    pool:
      vmImage: 'ubuntu-20.04'
    variables:
      CI: 1
      TCROOT: /tc/toolchain2-gcc84-x86-64
      GTEST_SHUFFLE: 0
      TILCK_NO_LOGO: 1
      GCC_TC_VER: 8.4.0
      ARCH: x86_64
    steps:
      - script: printenv
        displayName: Dump env
      - script: ./scripts/cmake_run
        displayName: Run CMake
      - script: make -j
        displayName: Build the kernel
