
jobs:
  - job: coverage_build
    container: 'vvaltchev/tilck_build:latest'
    pool:
      vmImage: 'ubuntu-18.04'
    variables:
      GTEST_SHUFFLE: 0
      DUMP_COV: 1
      REPORT_COV: 1
      TILCK_NO_LOGO: 1
    steps:
      - script: printenv
        displayName: Dump env
      - script: sudo mv /tilck_toolchain ./toolchain
        displayName: Move toolchain
      - script: ./scripts/build_generators/gcc_gcov
        displayName: Run CMake
      - script: make -j
        displayName: Build the kernel
      - script: make -j gtests
        displayName: Build the unit tests
      - script: ./build/gtests
        displayName: Run the unit tests
      - script: ./build/scripts/generate_test_coverage_report
        displayName: Gen unit tests coverage report
      - script: ./build/st/run_all_tests -c
        displayName: Run the system tests
      - script: ./build/scripts/generate_kernel_coverage_report --codecov
        displayName: Gen kernel gcov report and upload to codecov
        env:
          CODECOV_TOKEN: $(CODECOV_TOKEN)

  - job: build
    container: 'vvaltchev/tilck_build:latest'
    pool:
      vmImage: 'ubuntu-18.04'
    variables:
      GTEST_SHUFFLE: 0
      TILCK_NO_LOGO: 1
    strategy:
      matrix:
        release:
          GEN: 'gcc_rel'
        fast_release:
          GEN: 'gcc_fast_rel'
        arch_gtests:
          GEN: 'gcc_arch_gtests'
        nocow:
          GEN: 'gcc_nocow'
        no_nested_irq_tracking:
          GEN: 'gcc_no_nested_irq_tracking'
        minimal:
          GEN: 'minimal'
        syscc:
          GEN: 'gcc_syscc'
        clang:
          GEN: 'clang_wconv'
        clang_tc_isystem:
          GEN: 'clang_tc_isystem'
      maxParallel: 10
    steps:
      - script: printenv
        displayName: Dump env
      - script: sudo mv /tilck_toolchain ./toolchain
        displayName: Move toolchain
      - script: ./scripts/build_generators/$(GEN)
        displayName: Run CMake
      - script: make -j
        displayName: Build the kernel
      - script: make -j gtests
        displayName: Build the unit tests
      - script: ./build/gtests
        displayName: Run the unit tests
      - script: ./build/st/run_all_tests -c
        displayName: Run the system tests
