
notifications:
  email:
    on_success: never
    on_failure: always

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: cpp
      env: RELEASE=on
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - gcc-6-multilib
            - g++-6-multilib
            - nasm
            - binutils-multiarch
            - mtools

    - os: linux
      dist: trusty
      sudo: required
      language: cpp
      env: RELEASE=off USE_GCOV=on
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - gcc-6-multilib
            - g++-6-multilib
            - nasm
            - binutils-multiarch
            - mtools
 
before_install:
  - ./build_toolchain

install:
  - ./cmake_run
  - ./make_run
  - ./make_run gtests

script:
  - ./build/gtests
  - ./generate_coverage_report # Does nothing unless USE_GCOV is set
